services:
  myapp:
    build:
      context: ./../
      dockerfile: ./StudyCards.Api/Dockerfile
      args:
        - BUILD_CONFIGURATION=Release
    image: myapp:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT:
      SECRETS_APIKEY: 